CC=gcc
CFLAGS=-std=c11 -Wall -O -g
LDLIBS=-lm

VPATH= ./src

.SILENT: 

.PHONY: all

all:astringhe concatena mioatoi ostringhe paridispari \
	reverse ribalta_elenco somma_arr somma_mancanti somme_distinte \
	esad smista 

clean:
	rm -f *.o